In [173]:
import requests
import numpy as np
import pandas as pd
from pprint import pprint
import json
from urllib.request import urlopen, quote

In [174]:
# Import data to achieve location value
Loc = pd.read_csv("Data_Merge.csv")

In [175]:
Latitude = Loc.Latitude
Longitude = Loc.Longitude
LOC = pd.DataFrame()
LOC['Latitude'] = Latitude
la = LOC['Latitude']
LOC['Longitude'] = Longitude
lo = LOC['Longitude']

In [176]:
LOC.head(2)

    Latitude   Longitude
0  27.887752  102.273503
1  46.750948   82.987236

In [177]:
def temperature(data):
    api_address = 'http://api.openweathermap.org/data/2.5/weather?&appid=37eb773813f7219dab7d60cec5dfa6d6'
    #Latitude_l = input("Lat :")
    #Longitude_l = input("Lon :")
    latitude_l = data[0]
    longitude_l = data[1]

    url = api_address + "&lat=" + str(latitude_l) + "&lon=" + str(longitude_l)
    #data = requests.get(url)
    #res = data.json()
    req = urlopen(url)
    res = req.read().decode()
    temp = json.loads(res)
    temper = temp['main']['feels_like']
    return temper

In [178]:
data_list = []
for i in range(len(la)):
    row_list = []
    row_list.append(la[i])
    row_list.append(lo[i])
    data_list.append(row_list)

In [179]:
temp_data = []
for i in data_list:
    temp_data.append(temperature(i))

In [180]:
temp_data

[271.8,
 263.26,
 261.65,
 255.14,
 263.28,
 284.98,
 288.46,
 279.64,
 282.48,
 284.86,
 280.01,
 283.34,
 282.51,
 286.69,
 279.78,
 266.93,
 265.46,
 265.5,
 264.29,
 265.12,
 267.39,
 268.44,
 264.46,
 266.52,
 264.9,
 265.03,
 265.04,
 265.03,
 263.48,
 265.03,
 268.84,
 266.04,
 265.03,
 272.17,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 274.63,
 285.56,
 281.03,
 284.69,
 278.24,
 279.09,
 283.45,
 279.2,
 284.14,
 283.45,
 283.77,
 283.77,
 283.73,
 283.53,
 284.39,
 284.39,
 275.3,
 282.93,
 284.28,
 283.37,
 285.11,
 285.11,
 285.11,
 285.11,
 285.11,
 285.11,
 285.11,
 285.11,
 286.5,
 286.5,
 286.5,
 286.5,
 286.5,
 286.5,
 286.5,
 286.5,
 283.8,
 284.83,
 285.81,
 284.51,
 286.96,
 286.06,
 284.51,
 285.75,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 272.19,
 266.19,
 264.63,
 264.05,
 264.63,
 272.16,
 266.32,
 260.17,
 267.81,
 263.03,
 264.27,
 262.66,
 284.28,
 284.19,
 287.46,
 284.44,
 284.6,
 273.93,
 277.62,
 285.5,
 274.44,
 274.44,
 274.44,
 274.44,
 274.44,
 274.44,
 274.44,
 274.44,
 275.17,
 282.5,
 275.2,
 282.07,
 283.8,
 275.68,
 283.77,
 250.99,
 250.99,
 250.99,
 250.99,
 250.99,
 250.99,
 250.99,
 250.99,
 253.43,
 255.24,
 252.35,
 257.13,
 251.21,
 253.93,
 252.92,
 250.67,
 252.59,
 254.47,
 251.04,
 251.71,
 285.58,
 284.8,
 284.8,
 286.22,
 286.79,
 284.63,
 284.8,
 284.8,
 286.22,
 284.8,
 286.29,
 284.8,
 284.8,
 287.16,
 286.24,
 286,
 284.8,
 284.8,
 284.8,
 285.58,
 284.74,
 285.48,
 282.87,
 275.98,
 283.46,
 286,
 284.8,
 286.08,
 284.8,
 282.87,
 284.29,
 283.49,
 279.11,
 282.47,
 284.8,
 284.8,
 284.8,
 286.22,
 283.43,
 283.43,
 283.44,
 283.44,
 283.44,
 283.94,
 283.45,
 283.45,
 283.43,
 283.41,
 283.43,
 284.14,
 283.97,
 283.41,
 283.44,
 283.44,
 276.96,
 282.1,
 274.8,
 281.82,
 280.65,
 285.87,
 286.87,
 283.55,
 288.49,
 271.34,
 285.95,
 279.62,
 281.97,
 280.79,
 277.7,
 269.11,
 268.82,
 268.66,
 271.09,
 278.48,
 265.24,
 269.92,
 274.92,
 264.83,
 269.92,
 253.55,
 263.53,
 257.73,
 261.57,
 263.72,
 262.42,
 252.41,
 261.19,
 261.74,
 264.01,
 259.63,
 265.93,
 265.93,
 265.93,
 270.19,
 265.93,
 265.93,
 265.93,
 281.48,
 265.93,
 265.93,
 265.93,
 270.31,
 292.77,
 295.12,
 296.39,
 291.83,
 292.77,
 292.77,
 297.65,
 293.22,
 297.93,
 297.41,
 298.12,
 297.65,
 298.09,
 296.89,
 297.3,
 297.86,
 297.32,
 294.07,
 297.44,
 295.81,
 286.22,
 258.58,
 285.16,
 285.16,
 285.16,
 285.16,
 285.16,
 285.16,
 285.16,
 285.16,
 257.43,
 255.81,
 257.71,
 258.66,
 258.29,
 258.89,
 259.77,
 259.36,
 285.53,
 285.53,
 285.53,
 285.53,
 285.53,
 285.53,
 285.53,
 285.53,
 259.05,
 286.43,
 270.97,
 272.19,
 272.74,
 282.46,
 275.24,
 284.09,
 285.86,
 275.81,
 286.12,
 299.79,
 301.68,
 301.09,
 300.06,
 298.86,
 301.68,
 301.09,
 299,
 298.52,
 301.02,
 301.09,
 301.09,
 301.68,
 298.46,
 297.34,
 281.59,
 280.34,
 279.08,
 279.3,
 279.08,
 276.41,
 264.57,
 272.79,
 268.77,
 273.12,
 272.19,
 272.09,
 273.05,
 271.5,
 274.43,
 258.53,
 271.32,
 279.08,
 276.79,
 264.88,
 264.88,
 264.88,
 264.88,
 264.88,
 264.88,
 264.88,
 264.88,
 269.48,
 279.08,
 273.86,
 289.61,
 283.15,
 286.04,
 285.63,
 284.96,
 285.42,
 286.04,
 286.07,
 285.06,
 283.95,
 284.22,
 286.04,
 283.27,
 286.04,
 298.14,
 286.57,
 298.15,
 300.14,
 300.14,
 300.14,
 300.14,
 300.14,
 300.14,
 300.14,
 300.14,
 291.59,
 293.09,
 291.38,
 288.67,
 288.67,
 288.67,
 288.67,
 288.67,
 288.67,
 288.67,
 288.67,
 289.51,
 297.93,
 285.71,
 286.01,
 291.38,
 291.38,
 297.38,
 291.27,
 295.85,
 299.55,
 295.5,
 287.23,
 291.16,
 290.95,
 274.45,
 275.05,
 272.02,
 275.05,
 273.24,
 275.89,
 274.2,
 273.66,
 272.3,
 272.39,
 277.44,
 275.05,
 275.42,
 271.56,
 276.93,
 273.67,
 278.48,
 275.87,
 274.16,
 268.84,
 276.97,
 270.91,
 280.82,
 272.64,
 272.04,
 271.38,
 267.15,
 272.34,
 265.39,
 267.11,
 272.23,
 271.24,
 273.48,
 276.97,
 287.16,
 286.12,
 281.48,
 266.09,
 285.03,
 274.07,
 285.4,
 280.63,
 283.51,
 284.2,
 285.58,
 285.99,
 285.48,
 271.8,
 285.4,
 286.91,
 283.66,
 286.97,
 284.07,
 286.04,
 288.05,
 288.05,
 288.05,
 288.05,
 288.05,
 288.05,
 288.05,
 288.05,
 284.5,
 284.2,
 285.49,
 284.52,
 285.67,
 286.42,
 286.33,
 285.22,
 284.21,
 286.86]

In [181]:
Loc['Temperature_03_12'] = temp_data

In [182]:
Loc.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0_x,provinceName,provinceEnglishName,province_zipCode,cityName,cityEnglishName,city_zipCode,province_confirmedCount,...,耳鼻喉医院,肿瘤医院,胸科医院,脑科医院,诊所,骨科医院,Unnamed: 0_y,Population,Land_Area_mi2,Temperature_03_12
0,0,0,35,四川省,Sichuan,51,凉山,Liangshan,NaN,177,...,55.0,53.0,12.0,13,11546,379,NaN,4680000,23266.960,271.80
1,1,1,104,新疆维吾尔自治区,Xinjiang,65,塔城,Tacheng,654201.0,39,...,4.0,5.0,5.0,5,2438,18,NaN,924000,40365.436,263.26
2,2,2,140,青海省,Qinghai,63,西宁,Xining,630100.0,18,...,7.0,7.0,2.0,3,1611,29,322.0,"1,539,000",2846.000,261.65
3,3,3,141,青海省,Qinghai,63,海北州,Haibei,632200.0,18,...,7.0,7.0,2.0,3,1611,29,NaN,284300,13278.000,255.14
4,4,4,142,西藏自治区,Xizang,54,拉萨,Lhasa,540100.0,1,...,NaN,NaN,NaN,3,369,2,NaN,902500,11303.000,263.28

In [183]:
Loc.to_csv(r'Data_Merge_withTemp.csv', header=True, encoding='utf_8_sig')